name: Static Checks & Tests
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14-alpine
        env:
          POSTGRES_USER: pblubbs
          POSTGRES_PASSWORD: muppetverseofmadness
          POSTGRES_DB: bibliarius
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Setup Dependencies
        run: |
          make install
          poetry run python scripts/setup_db.py
      - name: Run Static Analysis
        run: |
          make lint
      - name: Run Tests
        run: |
          make test
